/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    CreateBg: typeof import('./src/components/widgets/CreateBg.vue')['default']
    CropperImg: typeof import('./src/components/widgets/CropperImg.vue')['default']
    CutoutImg: typeof import('./src/components/widgets/CutoutImg.vue')['default']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GroupPanel: typeof import('./src/components/panel/GroupPanel.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImagePanel: typeof import('./src/components/panel/ImagePanel.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    Lang: typeof import('./src/components/lang/index.vue')['default']
    PagePanel: typeof import('./src/components/panel/PagePanel.vue')['default']
    SharpPanel: typeof import('./src/components/panel/SharpPanel.vue')['default']
    ShortCut: typeof import('./src/components/widgets/ShortCut.vue')['default']
    TextPanel: typeof import('./src/components/panel/TextPanel.vue')['default']
  }
}
