/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    CanvasLeft: typeof import('./src/components/CanvasLeft/Index.vue')['default']
    CanvasLeftLabel: typeof import('./src/components/CanvasLeft/Label/index.vue')['default']
    CanvasLeftMenu: typeof import('./src/components/CanvasLeft/Menu/index.vue')['default']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/Header.vue')['default']
    Lang: typeof import('./src/components/lang/index.vue')['default']
    PanelGroupPanel: typeof import('./src/components/panel/GroupPanel.vue')['default']
    PanelImagePanel: typeof import('./src/components/panel/ImagePanel.vue')['default']
    PanelPagePanel: typeof import('./src/components/panel/PagePanel.vue')['default']
    PanelSharpPanel: typeof import('./src/components/panel/SharpPanel.vue')['default']
    PanelTextPanel: typeof import('./src/components/panel/TextPanel.vue')['default']
    WidgetsCreateBg: typeof import('./src/components/widgets/CreateBg.vue')['default']
    WidgetsCreateSketch: typeof import('./src/components/widgets/CreateSketch/Index.vue')['default']
    WidgetsCropperImg: typeof import('./src/components/widgets/CropperImg.vue')['default']
    WidgetsCutoutImg: typeof import('./src/components/widgets/CutoutImg.vue')['default']
    WidgetsImageExtraction: typeof import('./src/components/widgets/ImageExtraction/index.vue')['default']
    WidgetsModulesNumberSlider: typeof import('./src/components/widgets/modules/numberSlider.vue')['default']
    WidgetsShortCut: typeof import('./src/components/widgets/ShortCut.vue')['default']
  }
}
